CC = g++
DEFS = -DLINUX
FLAGS = -ansi -std=c++98 -fno-access-control -fno-elide-constructors -ffor-scope -fms-extensions
INCS = -I/
LIBS = -L/

all:
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameAI.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameApp.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameBase.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameLogic.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameWindow.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGamePhysics.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameGraphics.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameResource.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmGameSpawner.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmAI.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmActor.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmBomb.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmController.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmDoor.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmEffect.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmElevator.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmFerry.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmFlame.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmKey.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmLock.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmParticles.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmPawn.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmSmoke.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmTrigger.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmInventory.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmWeapon.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmSurface.cpp
	$(CC) -g -c $(DEFS) $(FLAGS) kgmSky.cpp

